galaxy_info:
  author: BOUAZIZ Mahdi & HAMDI Mahdi & KOUASSI Ismael
  description: This role installs containerd
  company: Finaxys
  min_ansible_version: 2.1

  platforms:
  - name: Debian
    versions:
    - all
    - 22

  galaxy_tags:
    - containerd

# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
dependencies: []

