---
############### Installing kubeadm, kubelet and kubectl  ###############
  - name: Install apt-transport-https, ca-certificates and curl
    vars:
      packages:
      - apt-transport-https 
      - ca-certificates 
      - curl
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  
  - name: Add GCP public signing key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: add kubernetes repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

  - name: Install kubelet kubeadm kubectl
    apt:
      name: 
        - kubelet=1.26.0-00  
        - kubeadm=1.26.0-00 
        - kubectl=1.26.0-00
      state: present
      update_cache: yes
  
  - name: Hold kubelet kubeadm kubectl
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop: 
      - kubeadm
      - kubectl
      - kubelet